"""
app/models/email_output.py
──────────────────────────
Pydantic model for structured LLM email output.
Forces the LLM to return validated JSON — no hallucinations.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, field_validator


class EmailOutput(BaseModel):
    """
    Structured email generated by the LLM.
    All fields are mandatory — the LLM must populate every field
    using real invoice data (no generic placeholders allowed).
    """

    invoice_id: str = Field(..., description="Must match the source invoice ID exactly")
    client_name: str = Field(..., description="Client's real name from invoice data")
    client_email: str = Field(..., description="Recipient email address")
    subject: str = Field(..., min_length=10, max_length=200, description="Professional email subject line")
    body: str = Field(..., min_length=100, description="Full email body with all required details")
    escalation_stage: int = Field(..., ge=1, le=5, description="Stage 1-5 per escalation matrix")
    tone: str = Field(..., description="Tone label matching the escalation stage")
    amount_due: float = Field(..., gt=0, description="Amount due as parsed from invoice")
    days_overdue: int = Field(..., ge=0, description="Number of days overdue")
    requires_legal_review: bool = Field(default=False, description="True if stage 5 (no email sent)")
    payment_link: str = Field(..., description="Personalised payment link for this invoice")
    risk_score: Optional[float] = Field(default=None, ge=0, le=100, description="AI payment risk score")
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    @field_validator("subject")
    @classmethod
    def no_placeholder_in_subject(cls, v: str) -> str:
        """Reject subjects containing generic placeholder text."""
        placeholders = ["[client]", "[company]", "[amount]", "[date]", "your name", "placeholder"]
        lowered = v.lower()
        for p in placeholders:
            if p in lowered:
                raise ValueError(f"Subject contains placeholder text: '{p}'")
        return v

    @field_validator("body")
    @classmethod
    def no_placeholder_in_body(cls, v: str) -> str:
        """Reject bodies containing generic placeholder text."""
        placeholders = ["[client name]", "[invoice number]", "[amount]", "[your name]", "[insert"]
        lowered = v.lower()
        for p in placeholders:
            if p in lowered:
                raise ValueError(f"Body contains placeholder text: '{p}'")
        return v

    class Config:
        json_schema_extra = {
            "example": {
                "invoice_id": "INV-2024-001",
                "client_name": "Acme Corp",
                "client_email": "billing@acmecorp.com",
                "subject": "Payment Reminder: Invoice INV-2024-001 — $5,000.00 Overdue",
                "body": "Dear Acme Corp,\n\nThis is a friendly reminder ...",
                "escalation_stage": 1,
                "tone": "warm_friendly",
                "amount_due": 5000.00,
                "days_overdue": 5,
                "requires_legal_review": False,
                "payment_link": "https://pay.acmefinance.com/invoice/INV-2024-001",
                "risk_score": 25.0,
            }
        }


class AuditRecord(BaseModel):
    """Record written to the audit_logs database table."""

    id: Optional[int] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    invoice_id: str
    client_name: str
    client_email: str
    escalation_stage: int
    days_overdue: int
    email_subject: Optional[str] = None
    email_body: Optional[str] = None
    send_status: str   # SENT | MOCK_SENT | FAILED | SKIPPED
    error_message: Optional[str] = None
    escalation_status: str  # NORMAL | ESCALATED_LEGAL
    risk_score: Optional[float] = None
    dry_run: bool = True
    run_id: Optional[str] = None   # LangGraph run ID for tracing
